Add LBO db-xrefs
monarch-initiative/vertebrate-breed-ontology pull request #168
Opened 2024-05-15 14:57 UTC by katiermullen

Closes #128

This PR updates 3 VBO spreadsheets:

1. "LBO ROBOT TEST" - this contains all of the terms from LBO to add in the normalization.
2. "update livestock" - this contains all of the terms from LBO which are NEW VBO terms.
3. "update DADIS country-breed" - this contains new columns (O-Q) for the parent terms for VBO breed-country terms that have an LBO-derived parent term. e.g new term VBO:0016929 Canchim (cattle) has children VBO:0002756 and VBO:0004467.

2024-05-15 23:14 UTC, sabrinatoro requested changes
I see for following for 'Adani (Goat)' dcterms:source: LBO:0001122|LBO:0001122
VBO:0017434 : LBO:0000716|ISBN:9781789241532|ISBN:9781845934668
There must be a "SPLIT=|" missing, though maybe it is incorrect since it is the same LBO ID.
(this is only for this term though)

2024-05-16 02:58 UTC, katiermullen commented
Fixed missing "SPLIT=|" and corrected  'Adani (Goat)' dcterms:source: LBO:0001122|LBO:0001122 error (LBO ID is repeated incorrectly.)

2024-05-16 14:54 UTC, sabrinatoro commented
That is perfect! Thank you @katiermullen! Approving and Merging.

2024-05-16 14:54 UTC, sabrinatoro approved these changes

2024-05-16 14:55 UTC, merged