dog-version1
monarch-initiative/vertebrate-breed-ontology pull request #79
Opened 2023-02-01 22:19 UTC by katiermullen

This branch adds dog breeds as well as definitions for "mixed breed" and "mixed breed (dog)"

2023-02-02 03:00 UTC, sabrinatoro commented
@katiermullen 
Great job! 
I think "mixed breed (dog)" should be under "dog" as it is a breed of dog. 
"mixed breed" should be in a template (though we don't have template set up yet), ie: all the mixed breed should follow the same pattern (ie the definition, and the axioms-though we haven't figured exactly how yet)
We will have "mixed cat", "mixed cattle",...), but they will not be one single "mixed breed" parent term.

2023-02-02 03:10 UTC, sabrinatoro requested changes

2023-02-02 03:12 UTC, katiermullen commented on src/ontology/components/breedstatus.owl
> +    <!-- http://purl.obolibrary.org/obo/VBO_0200902 -->
Oh, now I get it. This makes perfect sense.

2023-02-03 18:38 UTC, sabrinatoro approved these changes
GREAT job, Katie!!! 
It is ready to merge! (I will leave you the honors.

2023-02-03 18:42 UTC, merged